# Generated by Django 2.1.7 on 2019-06-12 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Formular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('largeur', models.IntegerField(null=True)),
                ('longueur', models.IntegerField(null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printingForm.Building')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printingForm.Format')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='formular',
            name='officeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printingForm.Office'),
        ),
    ]
