# Generated by Django 2.1.7 on 2019-05-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printingForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Formular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('dateFormRequest', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printingForm.Building')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printingForm.Format')),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='office',
        ),
        migrations.RemoveField(
            model_name='form',
            name='user',
        ),
        migrations.RemoveField(
            model_name='office',
            name='building',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.AddField(
            model_name='formular',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printingForm.Office'),
        ),
        migrations.AddField(
            model_name='formular',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printingForm.User'),
        ),
    ]
